package ontologia;

public enum Motivacion {
	TENER_TRABAJO, SALVAR_BUTTERCUP,VENGAR_PADRE,DECLARAR_GUERRA, GANAR_DINERO,SECUESTRAR_PRINCESA,ESTAR_CON_WEASLEY,
	SERVIR_PRINCIPE,ESTUDIAR_DOLOR,HUMILLAR_PRINCIPE
	
	//TODO QUIEN QUIERE ESTUDIAR DOLOR?
}
