package utilidades;

public enum Motivacion {
	TENER_TRABAJO, SALVAR_BUTTERCUP, VENGAR_PADRE,DECLARAR_GUERRA, GANAR_DINERO, SECUESTRAR_PRINCESA,ESTAR_CON_WESTLEY,
	SERVIR_PRINCIPE,ESTUDIAR_DOLOR,HUMILLAR_PRINCIPE, DESCONOCIDA
	
	//TODO QUIEN QUIERE ESTUDIAR DOLOR?
}
