package com.sample

import animales.*;
import lugares.*;
import personajes.*;
import relaciones.*;
import utilidades.*;
import java.util.*;
import profesiones.*;


//Creación de la base
rule "0.01 Creación Profesiones"
agenda-group "Acto0"
	then 
		insert(new Granjero());
		insert(new Indefinido());
		insert(new Pirateria());
end 

rule "0.02 Creación Lugares"
	then
		insert(new Granja());
		insert(new HabitacionN());
		insert(new Mar());
		insert(new BarcoPirata());	
end 

rule "0.03 Creación Animales"
	when 
		granja: Granja()
	then
		insert(new Caballo(granja));
		insert(new Cerdo(granja));
		insert(new Vaca(granja));
end

rule "0.04 Creación Personajes Acto 0"
	when 
		hab: HabitacionN()
	then
		insert(new Abuelo(hab));
		insert(new Madre(hab));
		insert(new Nieto(hab));
end

rule "0.05 Visita familiar"
  when
 	hab: HabitacionN()
    nt: Nieto(ubicacionActual == hab, estadoSalud == EstadoSalud.ENFERMO)
    ab: Abuelo(ubicacionActual == hab, estadoSalud == EstadoSalud.VIVO)
    md: Madre(ubicacionActual == hab, estadoSalud == EstadoSalud.VIVO)
    eval(nt.noTieneRelacion(ab))
    eval(ab.noTieneRelacion(md))
    eval(md.noTieneRelacion(nt))
  then
    FamiliarDe fm1 = new FamiliarDe(ab);
    FamiliarDe fm2 = new FamiliarDe(md);
    FamiliarDe fm3 = new FamiliarDe(nt);
    
    modify(nt){
    	addRelacion(fm1),
      	addRelacion(fm2);
    }
    
    modify(ab){
    	addRelacion(fm2),
    	addRelacion(fm3);
    }
    
    modify(md){
      	addRelacion(fm1),
     	addRelacion(fm3);
   	}
   	
  	Archivo.getUnicaInstancia().addInf(md.getNombre() + " está cuidando de " 
  	+ nt.getNombre() +" que se encuentra " + nt.getEstadoSalud().getString() 
  	+ " y llega su " +ab.getNombre() + " de visita. " );
end

rule "0.06 Nieto está enfermo"
when
	hab: HabitacionN()
    nt: Nieto(ubicacionActual == hab, estadoSalud == EstadoSalud.ENFERMO)
    ab: Abuelo(ubicacionActual == hab, estadoSalud == EstadoSalud.VIVO)
    md: Madre(ubicacionActual == hab, estadoSalud == EstadoSalud.VIVO)
    eval(nt.tieneRelacion(ab))
    eval(ab.tieneRelacion(md))
    eval(md.tieneRelacion(nt))
  then
  	modify(md){
  		setUbicacionActual(null);
  	}
  	Archivo.getUnicaInstancia().addInf(md.getNombre()+" se despide y "
  	+ ab.getNombre()+ " lee un cuento a " + nt.getNombre()+". ");
end

rule "0.07 Inicio cuento"
	when
		hab: HabitacionN()
		Nieto( ubicacionActual == hab )
		Abuelo( ubicacionActual == hab )
		Madre( ubicacionActual == null )
		granja: Granja()
		granjero: Granjero()
	then
		insert(new Westley(granja, granjero));
		insert(new Buttercup(granja, granjero));
		Archivo.getUnicaInstancia().addInf("El cuento es una historia de aventuras y amor.\n");
end

rule "0.08 Amor en la Granja"
	when
		g: Granja()
		gj: Granjero()
		wt: Westley( estadoSalud == EstadoSalud.VIVO, ubicacionActual == g, profesion == gj )
		bt: Buttercup( estadoSalud==EstadoSalud.VIVO, ubicacionActual == g, profesion == gj )
		eval(wt.noTieneRelacion(bt))
    	eval(bt.noTieneRelacion(wt))
	then
		Archivo.getUnicaInstancia().addInf(wt.getNombre() + " y " + bt.getNombre() + " son dos " 
		+ bt.getProfesion().toString()+"s. ");
		
		QuiereA q1 = new QuiereA(bt);
		QuiereA q2 = new QuiereA(wt);
		
		 modify(wt){
	      	addRelacion(q1),
	      	setMotivacion(Motivacion.ESTAR_CON_BUTTERCUP);
	    }
	    
	    modify(bt){
	    	addRelacion(q2),
	    	setMotivacion(Motivacion.ESTAR_CON_WESTLEY);
	    }
	    Archivo.getUnicaInstancia().addInf("Cuando " + bt.getNombre() + " le manda una tarea a " 
		+wt.getNombre() + ", él siempre contesta \"Como desees\", que en realidad significa \"Te amo\". "  );
end

rule "0.09 Westley se va a hacer fortuna"
    when
    	m: Mar()
   		g: Granja()
        wt: Westley( ubicacionActual == g, motivacion == Motivacion.ESTAR_CON_BUTTERCUP)
   		pir: Pirateria()
   		inf: Indefinido()
    then
    	
    	modify(wt){
    		setMotivacion(Motivacion.GANAR_DINERO),
    		setUbicacionActual(m),
    		setProfesion(inf);
    	}
     	Archivo.getUnicaInstancia().addInf("Como " + wt.getNombre()+ " no tiene dinero se marcha a " 
     	+ m.getNombre() + " para hacer fortuna. ");
     	insert (new Pirata(m, pir));
end

rule "0.10 Westley muere"
    when
    	m: Mar()
    	p: Pirateria()
        wt: Westley(ubicacionActual == m, estadoSalud==EstadoSalud.VIVO, motivacion == Motivacion.GANAR_DINERO)
   		pir: Pirata(ubicacionActual == m, estadoSalud==EstadoSalud.VIVO, profesion == p)
    then
    	modify(wt){
    		setEstadoSalud(EstadoSalud.MUERTO);
    	}
     	Archivo.getUnicaInstancia().addInf("En " +m.getNombre()+ " " + wt.getNombre() 
     	+ " es asesinado por " + pir.getNombre()+". ");
end

rule "0.11 Buttercup odia al pirata"
    when
    	g :Granja()
    	m: Mar()
    	b: BarcoPirata()
    	Westley(estadoSalud == EstadoSalud.MUERTO, ubicacionActual == m)
    	bt: Buttercup( ubicacionActual == g, motivacion == Motivacion.ESTAR_CON_WESTLEY)
    	pr: Pirata( ubicacionActual == m )
    then
    	OdiaA od1 = new OdiaA(pr);
    	OdiadoPor od2 = new OdiadoPor(bt);
    	
	    modify(bt){
	        addRelacion(od1),
	        setMotivacion(Motivacion.DESCONOCIDA);
	    }
	 
	    modify(pr){
	    	setUbicacionActual(b),
	        addRelacion(od2);
	    }
	    Archivo.getUnicaInstancia().addInf(bt.getNombre()+ " " +bt.getRelacion(pr).toString() + 
	    " por la muerte de Westley y pierde su motivación. ");
end

rule "0.12 Relacion Conocer"
    when
        p1 : Personaje(ubicacionActual != null)
        p2 : Personaje(nombre != p1.getNombre(), ubicacionActual == p1.getUbicacionActual() )
        eval (p1.noTieneRelacion(p2))
    then

        Relacion r = new ConoceA(p2);
        Relacion r2 = new ConocidoDe(p1);
        modify(p1){
        	addRelacion(r);
        }
        modify(p2){
        	addRelacion(r2);
        } 
end
//Fin acto0

// Inicio Acto1
rule "1.01 Lugares Acto1"
agenda-group "Acto1"
	then
		insert(new BarcoMercenarios());
		insert(new Castillo());
		insert(new Espana());
		insert(new Bosque());
		insert(new AcantiladosLocura());
		insert(new CaminoMontana());
		insert(new CaminoRocoso());
end

rule"1.02 Profesiones Acto1"
	then
		insert(new Mercenario());
		insert(new Gobernante());
		insert(new Visir());
		insert(new Herrero());
		insert(new Desempleado());
end

rule "1.03 Creación de Personajes Acto1"
	when 
		mercenario: Mercenario()
		gobernante: Gobernante()
		visir: Visir()
		castillo: Castillo()
		esp : Espana()
		herrero: Herrero()
		bosque: Bosque()
		mar: Mar()
	then
		insert(new Vizzini(bosque, mercenario ));
		insert(new Inigo(bosque, mercenario));
		insert(new Fezzik(bosque, mercenario));
		insert(new Rey(castillo, gobernante));
		insert(new Principe(castillo, gobernante));
		insert(new Conde(castillo, visir));
		insert(new PadreInigo(esp, herrero));
		insert(new AnguilaChillona(mar));
end

rule "1.4 El Rey"
	when
		g: Gobernante()
		r: Rey(profesion == g)
		eval(r.noTieneTitulo())
	then
		modify(r){
			setTit(TituloNobiliario.REY);
		}
end

rule "1.5 El Príncipe"
	when
		g: Gobernante()
		p: Principe(profesion == g)
		eval(p.noTieneTitulo())
	then
		modify(p){
			setTit(TituloNobiliario.PRINCIPE);
		}
		
end
rule "1.6 El Conde"
	when
		v: Visir()
		c: Conde( profesion==v )
		eval(c.noTieneTitulo())
	then
		modify(c){
			setTit(TituloNobiliario.CONDE);
		}
end

rule "1.7 Rey y Príncipe son familia"
  when
  	g: Gobernante()
    pr: Principe(profesion == g)
    ry: Rey(profesion == g)
    eval(pr.esConocido(ry))
  then
  	Relacion r1 = pr.getRelacion(ry);
  	Relacion r2 = ry.getRelacion(pr);
    FamiliarDe fm1 = new FamiliarDe(ry);
    FamiliarDe fm2 = new FamiliarDe(pr);
    
    modify(pr){
    	removeRelacion(r1),
      	addRelacion(fm1);
    }
    modify(ry){
    	removeRelacion(r2),
      	addRelacion(fm2);
    }
end

rule "1.8 Principe y Conde amigos"
  when
  	g: Gobernante()
  	v: Visir()
    pr: Principe( profesion == g)
    cd: Conde(profesion ==v )
    eval(pr.esConocido(cd))
  then
  	Relacion r1 = pr.getRelacion(cd);
  	Relacion r2 = cd.getRelacion(pr);
    Relacion am1 = new AmigoDe(cd);
    Relacion am2 = new AmigoDe(pr);
    
    modify(pr){
    	removeRelacion(r1),
      	addRelacion(am1);
    }
    
    modify(cd){
    	removeRelacion(r2),
      	addRelacion(am2),
      	setMotivacion(Motivacion.SERVIR_PRINCIPE);
    }
end

rule "1.9 El príncipe quiere a Buttercup"
  when
    pr: Principe(estadoSalud == EstadoSalud.VIVO)
    bt: Buttercup( )
    eval(pr.noTieneRelacion(bt))
  then
    QuiereA q1 = new QuiereA(bt);
    modify(pr){
          addRelacion(q1),
          setMotivacion(Motivacion.ESTAR_CON_BUTTERCUP);
    }
    Archivo.getUnicaInstancia().addInf(pr.getNombre() + " quiere a " + bt.getNombre()+ ".");
end

rule "1.4 Buttercup prometida del príncipe"
  when
  	m: Mar()
    pr: Principe(motivacion == Motivacion.ESTAR_CON_BUTTERCUP)
    bt: Buttercup( )
    Westley( estadoSalud == EstadoSalud.MUERTO, ubicacionActual == m)
    c: Castillo()
    eval(bt.noTieneRelacion(pr))
  then
    Relacion p1 = new PrometidaDe(pr);
    Relacion p2 = new PrometidoDe(bt);
    modify(bt){
          addRelacion(p1),
          setUbicacionActual(c);
    }
    modify(pr){
          addRelacion(p2);
    }
    
    Archivo.getUnicaInstancia().addInf("El Príncipe y Buttercup se prometen y se anuncia la boda.");
end

rule "1.5 Buttercup sale a pasear"
	when
		b: Bosque()
		c: Castillo()
		bt: Buttercup(ubicacionActual == c)
		we: Westley(estadoSalud == EstadoSalud.MUERTO)
		Principe(ubicacionActual == c, motivacion == Motivacion.ESTAR_CON_BUTTERCUP )
	then
		modify(bt){
			setUbicacionActual(b);
		}
	    Archivo.getUnicaInstancia().addInf("Buttercup sale a pasear al bosque.");
end			

rule "1.6 Secuestro Buttercup"
	when
		b: Bosque();
		princesa: Buttercup(ubicacionActual == b)
		mer: Mercenario()
		v: Vizzini(ubicacionActual == b, profesion == mer)
		i: Inigo(ubicacionActual == b, profesion == mer)
		f: Fezzik(ubicacionActual == b, profesion == mer)
	then
		modify(i){
			setMotivacion(Motivacion.SECUESTRAR_PRINCESA);
		}
		modify(f){
			setMotivacion(Motivacion.SECUESTRAR_PRINCESA);
		}
		modify(v){
			setMotivacion(Motivacion.SECUESTRAR_PRINCESA);
		}
		Archivo.getUnicaInstancia().addInf(v.getNombre() + "," + i.getNombre() + " y " + f.getNombre() + " secuestran a "+ princesa.getNombre()+".");
end

rule "1.7 Huida por el mar"
	when
		b: Bosque();
		princesa: Buttercup(ubicacionActual == b)
		mer: Mercenario()
		v: Vizzini(ubicacionActual == b, profesion == mer, motivacion == Motivacion.SECUESTRAR_PRINCESA)
		i: Inigo(ubicacionActual == b, profesion == mer)
		f: Fezzik(ubicacionActual == b, profesion == mer)
		mar: Mar()
	then
		modify(v){
			setMotivacion(Motivacion.DECLARAR_GUERRA),
			setUbicacionActual(mar);
		}
		modify(princesa){
			setUbicacionActual(mar);
		}
		modify(i){
			setUbicacionActual(mar);
		}
		modify(f){
			setUbicacionActual(mar);
		}
		Archivo.getUnicaInstancia().addInf("Los mercenarios se llevan a Buttercup por el mar para llegar a la frontera de Guilder.");
		
end

rule "1.8 Anguila ataca a buttercup"
	when 
		m: Mar();
		bt: Buttercup(ubicacionActual == m )
		a: AnguilaChillona(ubicacionActual == m)
	then 
		modify(bt){
			setEstadoSalud(EstadoSalud.EN_PELIGRO);
		}
		
		Archivo.getUnicaInstancia().addInf(bt.getNombre() + " intenta escapar y en el agua es atacada por " + a.getNombre() + ", ahora ella está " + bt.getEstadoSalud().getString() +".");
end

rule "1.9 Fezzik salva a Buttercup"
	when 
		m: Mar()
		bt: Buttercup( estadoSalud == EstadoSalud.EN_PELIGRO, ubicacionActual == m )
		fz: Fezzik( ubicacionActual == m )
		a: AnguilaChillona( ubicacionActual== m)
	then
		modify(bt){
			setEstadoSalud(EstadoSalud.VIVO);
		}
		modify(a){
			setEstadoSalud(EstadoSalud.MUERTO);
		}		
		Archivo.getUnicaInstancia().addInf(fz.getNombre()+" salva a " + bt.getNombre() + ", la anguila muere.");		
end

rule "1.10 Llegada a los acantilados"
	when
		m: Mar( )
		b:BarcoPirata()
		acantilados: AcantiladosLocura(  )
		an: AnguilaChillona(ubicacionActual == m , estadoSalud == EstadoSalud.MUERTO)
		v: Vizzini( ubicacionActual == m)
		bt: Buttercup(ubicacionActual == m)
		f: Fezzik( ubicacionActual == m)
		i: Inigo( ubicacionActual == m)
		p: Pirata( ubicacionActual == b )
	then
		modify(i){
			setUbicacionActual(acantilados)
		}
		modify(f){
			setUbicacionActual(acantilados)
		}
		modify(bt){
			setUbicacionActual(acantilados)
		}
		modify(v){
			setUbicacionActual(acantilados)		
		}
		modify(p){
			setMotivacion(Motivacion.SECUESTRAR_PRINCESA)
		}
		Archivo.getUnicaInstancia().addInf(v.getNombre() + "," + f.getNombre() + "," + i.getNombre() + "y" + bt.getNombre() + " llegan a " + acantilados.getNombre());
		Archivo.getUnicaInstancia().addInf(p.getNombre() + " quiere " + p.getMotivacion().getString());
end

rule "1.11 Pirata llega a los acantilados"
	when
		b: BarcoPirata()
		cm: CaminoMontana()
		ac: AcantiladosLocura()
		p: Pirata( ubicacionActual == b )
		i: Inigo( ubicacionActual == ac )
		v: Vizzini(ubicacionActual == ac, estadoSalud == EstadoSalud.VIVO)
		bt: Buttercup(ubicacionActual == ac, estadoSalud == EstadoSalud.VIVO)
		f: Fezzik(ubicacionActual == ac, estadoSalud == EstadoSalud.VIVO)
	then
		modify(p){
			setUbicacionActual(ac)
		}
		modify(bt){
			setUbicacionActual(cm)
		}
		modify(v){
			setUbicacionActual(cm)
		}
		modify(f){
			setUbicacionActual(cm)
		}
		Archivo.getUnicaInstancia().addInf(v.getNombre() + "," + f.getNombre() + " y " + bt.getNombre() + " huyen a " + cm.getNombre());
		Archivo.getUnicaInstancia().addInf( p.getNombre() + " llega a " + ac.getNombre());
end

rule "1.12 Historia Domingo Montoya"
	when
		ac: AcantiladosLocura()
		p: Pirata( ubicacionActual == ac )
		i: Inigo( ubicacionActual == ac )
		pi: PadreInigo(estadoSalud == EstadoSalud.MUERTO)
	then
		Relacion fm1 = new FamiliarDe(pi);
	    Relacion fm2 = new FamiliarDe(i);
	    ArrayList<Relacion> listaR = i.getRelacionesPersonaje();
	    listaR.add(fm1);
	    
	    modify(i){
	      setRelacionesPersonaje(listaR);
	    }
	    ArrayList<Relacion> listaR2 = pi.getRelacionesPersonaje();
	    listaR2.add(fm2);
	    modify(pi){
	      setRelacionesPersonaje(listaR2);
	    }
		modify(i){
			setMotivacion(Motivacion.VENGAR_PADRE);
		}
		Archivo.getUnicaInstancia().addInf("Domingo Montoya está muerto y su hijo " + i.getNombre() + " busca venganza");
end

rule "1.13 Pirata vence a Iñigo"
	when
		ac: AcantiladosLocura()
		cm: CaminoMontana()
		mercenario: Mercenario()
		p: Pirata(ubicacionActual == ac)
		i: Inigo(ubicacionActual == ac, profesion == mercenario, estadoSalud == EstadoSalud.VIVO)
	then
		modify(i){
			setEstadoSalud(EstadoSalud.INCONSCIENTE)
		}
		modify(p){
			setUbicacionActual(cm)
		}
		Archivo.getUnicaInstancia().addInf(p.getNombre() + " vence a " + i.getNombre() +" y sigue la persecución");
		
end 

rule "1.14 Pirata vence a Fezzik"
	when
		cm : CaminoMontana()
		ac: AcantiladosLocura()
		des: Desempleado()
		p: Pirata(ubicacionActual == cm)
		f: Fezzik(ubicacionActual == cm, estadoSalud == EstadoSalud.VIVO)
		i: Inigo(estadoSalud == EstadoSalud.INCONSCIENTE, ubicacionActual == ac)
	then
		modify(f){
			setEstadoSalud(EstadoSalud.INCONSCIENTE)
		}
		modify(i){
			setUbicacionActual(null)
		}
		
		Archivo.getUnicaInstancia().addInf(p.getNombre() + " vence a " + f.getNombre());
end

rule "1.15 Principe llega a los acantilados"
	when
		ac: AcantiladosLocura()
		cm: CaminoMontana()
		des: Desempleado()
		p: Pirata(ubicacionActual == cm)
		f: Fezzik(ubicacionActual == cm, estadoSalud == EstadoSalud.INCONSCIENTE)
		pr: Principe(motivacion == Motivacion.ESTAR_CON_BUTTERCUP)
		cd: Conde()
	then
		modify(pr){
			setUbicacionActual(ac)
		}
		modify(cd){
			setUbicacionActual(ac)
		}
		modify(pr){
			setMotivacion(Motivacion.SALVAR_BUTTERCUP);
		}
		modify(f){
			setUbicacionActual(null),
			setEstadoSalud(EstadoSalud.INCONSCIENTE);
		}
		
		Archivo.getUnicaInstancia().addInf("Príncipe llega a los acantilados para salvar a Buttercup");
end 

rule "1.16 Muere Vizzini"
	when 
		cm : CaminoMontana()
		p: Pirata(ubicacionActual == cm, estadoSalud == EstadoSalud.VIVO)
		v: Vizzini(ubicacionActual == cm, estadoSalud == EstadoSalud.VIVO)
		des: Desempleado()
		i: Inigo(estadoSalud == EstadoSalud.INCONSCIENTE)
		f: Fezzik(estadoSalud == EstadoSalud.INCONSCIENTE)
	then 
		modify(v){
			setEstadoSalud(EstadoSalud.MUERTO);
		}
		modify(i){
			setProfesion(des);
		}
		modify(f){
			setProfesion(des);
		}
		Archivo.getUnicaInstancia().addInf("Vizzini está " + v.getEstadoSalud().getString() + " por " + p.getNombre());
end
//Las ubicaciones y empleos de Fezzik e Íñigo ya han sido modificadas en las reglas anteriores, 
//ya no hay que modificarlo en el acto2

/*** ACTO 2 El	príncipe	sigue	las	huellas	hasta	que	se	produce	el beso	de	amor	verdadero****/
rule "Creación Acto2"
agenda-group "Acto2"
	then
		insert(new Colina());
		insert(new Espadachin());
		System.out.println("Acto2");	
end 
rule "2.1 Pirata y Buttercup huyen"
	when 
		camino : CaminoMontana()
		v: Vizzini(estadoSalud == EstadoSalud.MUERTO)
		b: Buttercup(ubicacionActual == camino)
		p: Pirata(ubicacionActual == camino)
		colina: Colina()
	then 
		modify(b){
			setUbicacionActual(colina)
		}
		modify(p){
			setUbicacionActual(colina)
		}
		Archivo.getUnicaInstancia().addInf("El pirata y Buttercup huyen hacia la colina");
end

rule "2.2 Principe rastrea a Buttercup"
	when 
		ac: AcantiladosLocura()
		pirata: Pirata(ubicacionActual != ac) //soolo llega cuando ya no esten alli.
		p: Principe(ubicacionActual == ac)
		cm: CaminoMontana()
		conde: Conde(ubicacionActual == ac)
		co: Colina()
	then 
		modify(p){
			setUbicacionActual(cm)
		}
		modify(conde){
			setUbicacionActual(cm)
		}
		Archivo.getUnicaInstancia().addInf(p.getNombre() + " rastrea a su prometida hasta "+ cm.getNombre());
end 

rule "2.3 Buttercup descubre quien es su secuestrador"
	when 
		colina: Colina()
		but: Buttercup(ubicacionActual == colina)
		pir: Pirata(ubicacionActual == colina)
	then 
		Archivo.getUnicaInstancia().addInf(but.getNombre() +" descubre que ha sido secuestrada por " + pir.getNombre());
	
end

rule "2.4 Principe alcanza a la princesa"
	when 
		co: Colina()
		cm: CaminoMontana()
		but: Buttercup(ubicacionActual == co)
		pir: Pirata(ubicacionActual == co)
		prin: Principe(ubicacionActual == cm)
		conde: Conde(ubicacionActual == cm)
	then 
		modify(prin){
			setUbicacionActual(co)
		}
		modify(conde){
			setUbicacionActual(co)
		}
		Archivo.getUnicaInstancia().addInf(prin.getNombre() + " alcanza a la princesa en " + co.getNombre());
end

rule "2.5 Como Desees en la colina"
	when 
		co: Colina()
		we: Westley(estadoSalud == EstadoSalud.MUERTO)
		bu: Buttercup(ubicacionActual == co)
		pr: Principe (ubicacionActual == co)
		pi: Pirata(ubicacionActual == co)
		es: Espadachin()
		
	then 
		Archivo.getUnicaInstancia().addInf(bu.getNombre() + " empuja a " + pi.getNombre()+ " y grita: COMO DESEES.");
		modify(we){
			setEstadoSalud(EstadoSalud.VIVO),
			setUbicacionActual(co),
			setProfesion(es);
		}
		Archivo.getUnicaInstancia().addInf(bu.getNombre() + " se tira por " + co.getNombre());
		Archivo.getUnicaInstancia().addInf("Se produce el beso de amor verdadero");
		
//no se que hacer con el principe ni el pirata xD
		
end
/*
rule "ubicacionPirata"
	when
		w: Westley(estadoSalud == EstadoSalud.VIVO)
		p: Pirata(ubicacionActual != w.getUbicacionActual)
	then 
		modify(p){
			setUbicacionActual(w.getUbicacionActual());
		}
end 
*/



/*** ACTO 3  Buttercup	y	Westley	llegan	al	pantano	hasta que	muere	el	rey****/

rule "Creacion Acto3"
	agenda-group "Acto3"
	then 
		insert(new PantanoFuego());
		insert(new PozoDesesperacion());
		System.out.println("Acto3");
end 

rule "3.1 Necesario Acto3"
	when 
		p: PantanoFuego()
	then
		insert(new RoedorAspectoGigantesco(p));
end 

rule "3.2 Adentrar en el pantano"
	when 
		co: Colina()
		bu: Buttercup(ubicacionActual == co)
		pa: PantanoFuego()
		we: Westley(estadoSalud == EstadoSalud.VIVO,ubicacionActual == co)
		pr: Principe(ubicacionActual == co)
	then
		modify(bu){
			setUbicacionActual(pa);
		}
		modify(we){
			setUbicacionActual(pa);
		}
		Archivo.getUnicaInstancia().addInf(bu.getNombre() +" y " + we.getNombre() + " se adentran en " +pa.getNombre());
end 

rule "3.3 Primer Horror"
	when
		pa: PantanoFuego()
		we: Westley(ubicacionActual == pa)
		bu: Buttercup(ubicacionActual == pa)
	then
		Archivo.getUnicaInstancia().addInf(we.getNombre() + " y " +bu.getNombre() +" superan las erupciones de fuego, ya que son precedidas de un sonido de burbuja");
end 

rule "3.4 Leyenda del capitan Robert"
	when
		pa: PantanoFuego()
		we: Westley(ubicacionActual == pa)
		bu: Buttercup(ubicacionActual == pa)
		es: Espadachin()
	then 
		Archivo.getUnicaInstancia().addInf(we.getNombre() + " cuenta a " + bu.getNombre() + " como el capitan Robert le hace ayudante");
		modify(we)}{
			setProfesion(es);
		}
end 	

rule "3.5 Segundo Horror" 
	when 
		pa: PantanoFuego()
		we: Westley(ubicacionActual == pa)
		bu: Buttercup(ubicacionActual == pa)
	then 
		Archivo.getUnicaInstancia().addInf(we.getNombre() + " y " +bu.getNombre() + " superan el segundo horror: las arenas resplandecientes, ya que saben que aspecto tienen");
end

rule "3.6 Tercer Horror"
	when 
		pa: PantanoFuego()
		we: Westley(ubicacionActual == pa)
		bu: Buttercup(ubicacionActual == pa)
		rag: Animal(ubicacionActual == pa)		
	then 
		modify(rag){
			setEstadoSalud(EstadoSalud.MUERTO);
		}
		Archivo.getUnicaInstancia().addInf(we.getNombre() + " mata a " + rag.getNombre());
		Archivo.getUnicaInstancia().addInf(we.getNombre() + " y " + bu.getNombre() + " superan el tercer horror");
end 

rule "3.7 Principe va a la salida del pantano"
	when 
		pa: PantanoFuego()
		co: Colina()
		we: Westley(ubicacionActual == pa)
		bu: Buttercup(ubicacionActual == pa)
		pr: Principe (ubicacionActual == co)
		bo: Bosque()
		conde: Conde(ubicacionActual == co)
	then 
		modify(pr){
			setUbicacionActual(bo);
		}
		modify(conde){
			setUbicacionActual(bo);
		}
		Archivo.getUnicaInstancia().addInf(pr.getNombre() + " va a " + pr.getUbicacionActual());
end 

rule "3.8 Salen del pantano de fuego"
	when 
		pa: PantanoFuego()
		bo: Bosque()
		we: Westley(ubicacionActual == pa)
		bu: Buttercup(ubicacionActual == pa)
		rag: Animal(ubicacionActual == pa, estadoSalud == EstadoSalud.MUERTO)
		pr: Principe(ubicacionActual == bo)
	then 
		modify(bu){
			setUbicacionActual(bo);
		}
		modify(we){
			setUbicacionActual(bo);
		}
		Archivo.getUnicaInstancia().addInf(we.getNombre() + " y " + bu.getNombre() + " salen de " + pa.getNombre() + " encontrandose con " + pr.getNombre());
end 

rule "3.9 promesa de vida"
	when 
		bo: Bosque()
		ca: Castillo()
		we: Westley(ubicacionActual == bo)
		bu: Buttercup(ubicacionActual == bo)
		pr: Principe(ubicacionActual == bo)		
		conde: Conde(ubicacionActual == bo)
		po: PozoDesesperacion()
	then 
		Archivo.getUnicaInstancia().addInf(bu.getNombre() + " se entrega, con la condicion de que " + we.getNombre() + " seguira " + we.getEstadoSalud());
		modify(we){
			setUbicacionActual(po);
		} 
		modify(bu){
			setUbicacionActual(ca);
		}
		modify(pr){
			setUbicacionActual(ca);
		}
		modify(conde){
			setUbicacionActual(ca);
		}
		
		Archivo.getUnicaInstancia().addInf(we.getNombre() + " descubre que " + conde.getNombre() + " tiene 6 dedos");
		Archivo.getUnicaInstancia().addInf(conde.getNombre() + "," + bu.getNombre() + " y " + pr.getNombre() + " van al  Castillo");
end 

//Westley en el pozo

//Muerte del rey

/*** ACTO 4 	Presentación	de	la	Nueva	Reina	hasta la	muerte de	Westley ****/

rule "Creacion Acto4"
agenda-group "Acto4"
	then
		insert(new Guardia());
		insert(new PatioCastillo());
		// insertar bosque de ladrones??
		insert(new BosqueLadrones());
		// insertar Aposentos princesa??
		insert(new AposentosPrincesa());
		System.out.println("Acto 4");
end

rule "4.1 Creación de Personajes Acto4"
	when
		pa: PatioCastillo()
		ca: Castillo()
		ind: Indefinido()
		gu: Guardia()
	then
		insert(new Anciana(pa,ind));
		insert(new Yalin(ca, gu));
		Archivo.getUnicaInstancia().addInf("\n Acto 4\n");	
end


rule "4.2 Sueño Buttercup"
	when
		ca: Castillo()
		pa: PatioCastillo()	
		wes: Westley()
		rey: Rey()
		an: Anciana(ubicacionActual == pa)
		conde: Conde(ubicacionActual == ca)
		bu: Buttercup(ubicacionActual == ca)
		pr: Principe (ubicacionActual == ca)
	then

		modify(conde){
			setUbicacionActual(pa);
		} 
		modify(bu){
			setUbicacionActual(pa);
		}
		modify(pr){
			setUbicacionActual(pa);
		}	
		modify(an){
			setUbicacionActual(null);
		}
		Archivo.getUnicaInstancia().addInf(bu.getNombre() + " sueña que " + rey.getNombre() + " muere y se casa con " + pr.getNombre());
		Archivo.getUnicaInstancia().addInf(an.getNombre() + " abuchea a " + bu.getNombre() + " por no casarse con " + wes.getNombre() + " y renunciar al amor verdadero");	
		
end

rule "4.3 Trato principe"
	when
	ca: Castillo()
	pa: PatioCastillo()
	po: PozoDesesperacion()
	pr: Principe (ubicacionActual == pa)
	bu: Buttercup(ubicacionActual == pa)
	conde: Conde(ubicacionActual == pa)
	we: Westley(ubicacionActual == po)
		
	then
		modify(conde){
			setUbicacionActual(ca);
		} 
		modify(bu){
			setUbicacionActual(ca);
		}
		modify(pr){
			setMotivacion(Motivacion.DECLARAR_GUERRA),
			setUbicacionActual(ca);
		}
		modify(we){
			setEstadoSalud(EstadoSalud.EN_PELIGRO);
		}
		
		Archivo.getUnicaInstancia().addInf(pr.getNombre() + " hace un trato con " + bu.getNombre() + " para casarse con ella");
		Archivo.getUnicaInstancia().addInf(pr.getNombre() + " planea matar a " + bu.getNombre() + " para incriminar a la nacion enemiga y declarar la guerra");
	
end

//REGLA SE DESCUBRE QUE PRINCIPE QUIERE MATAR A BUTTERCUP
/*rule "4.3.1 Plan para declarar la guerra a Guilder"
	when
		
	then
		
end*/

rule "4.4 Tortura a Westley"
	when
	po: PozoDesesperacion()
	ca: Castillo()
	wes: Westley(ubicacionActual == po, estadoSalud == EstadoSalud.EN_PELIGRO)
	conde: Conde(ubicacionActual == ca)
	
	then
		modify(conde){
			setUbicacionActual(po);
		}
		Archivo.getUnicaInstancia().addInf(conde.getNombre() + " tortura a " + wes.getNombre() + " en " + po.getNombre()); 
	
end

// no funciona?? (Arreglado) -> BOsque de ladrones insertado en consulta 4
rule "4.5 Pricipe ordena a Yalin"
	when
		ca: Castillo()
		bl: BosqueLadrones()
		pr: Principe (ubicacionActual == ca, motivacion == Motivacion.DECLARAR_GUERRA)
		ya: Yalin(ubicacionActual == ca)
	then
		Archivo.getUnicaInstancia().addInf(pr.getNombre() + " ordena a " + ya.getNombre() + " vaciar " + bl.getNombre());
		modify(ya){
			setUbicacionActual(bl);
		}
		insert(new BrigadaBrutal());
end

rule "4.6 Reencuentro Iñigo y Fezzik"
	when
		// ubicacion actual ????
		bl: BosqueLadrones()
		des: Desempleado( )
		br: BrigadaBrutal()
		i: Inigo(ubicacionActual == null, profesion==des)
		fe: Fezzik(ubicacionActual == null)
		ya: Yalin( ubicacionActual == bl )
	then
		modify(i){
			setUbicacionActual(bl),
			setEstadoSalud(EstadoSalud.BORRACHO);
		}
		modify(fe){
			setUbicacionActual(bl),
			setProfesion(br);			
		}
		
		Archivo.getUnicaInstancia().addInf(fe.getNombre() + " encuentra borracho a " + i.getNombre() + " en " + bl.getNombre());
		modify(ya){
			setUbicacionActual(null);
		}
end


rule "4.7 Iñigo y Fezzik buscan a Westley"
	when
		bl: BosqueLadrones()
		conde: Conde()
		i: Inigo(ubicacionActual == bl, estadoSalud == EstadoSalud.BORRACHO)
		fe: Fezzik(ubicacionActual == bl)
	then
		modify(i){
			setEstadoSalud(EstadoSalud.RECUPERADO);
		}
		
		Archivo.getUnicaInstancia().addInf(fe.getNombre() + " ayuda a " + i.getNombre() + " a recuperarse");
		
		Archivo.getUnicaInstancia().addInf(i.getNombre() + " se entera de quien es realmente " + conde.getNombre());

end

rule "4.8 Buttercup descubre mentira Principe"
	when
		ca: Castillo()
		ap: AposentosPrincesa()
		po: PozoDesesperacion()
		bu: Buttercup(ubicacionActual == ca)
		pr: Principe(ubicacionActual == ca)
		Westley( ubicacionActual ==po )
	then
		modify (bu){
			setUbicacionActual(ap);
		}
		modify (pr){
			setUbicacionActual(po);
		}
		Archivo.getUnicaInstancia().addInf(bu.getNombre() + " descubre la mentira de " + pr.getNombre() + " en " + ca.getNombre());
		Archivo.getUnicaInstancia().addInf(bu.getNombre() + " insulta a " + pr.getNombre() + " y este la encierra en " + ap.getNombre());
		

end

rule "4.9 Tortura extrema a Westley"
	when
		po: PozoDesesperacion()
		ca: Castillo()
		pr: Principe(UbicacionActual == po)
		wes: Westley(ubicacionActual == po)
		conde: Conde(ubicacionActual == po)
	then
	//creo que no hace falta que el principe este en el pozo, si se pone luego tenemos que echarlo
		
		modify(wes){
			setEstadoSalud(EstadoSalud.MUERTO);
		}
		
		Archivo.getUnicaInstancia().addInf(pr.getNombre() + " tortura de forma extrema a " + wes.getNombre() + " en " + po.getNombre());  
		//hace falta mandar al conde al castillo
		modify(conde){
			setUbicacionActual(ca);
		}
		modify (pr){
			setUbicacionActual(ca);
		}

end
 
 
rule "4.10 Iñigo y Fezzik encuentran a Westley"
	when
		bl: BosqueLadrones()
		po: PozoDesesperacion()
		i: Inigo(ubicacionActual == bl, estadoSalud==EstadoSalud.RECUPERADO)
		fe: Fezzik(ubicacionActual == bl)
		wes: Westley(ubicacionActual == po)
		pi: PadreInigo()
		bb: BrigadaBrutal()
		co: Conde(ubicacionActual != po) // como condicion que el conde no este en el pozo
	then
		modify(i){
			setEstadoSalud(EstadoSalud.VIVO),
			setUbicacionActual(po);
		}
		modify(fe){
			setUbicacionActual(po);
		}
		Archivo.getUnicaInstancia().addInf(i.getNombre() + " y " + fe.getNombre() + " se encuentran con el sirviente y lo interrogan hasta que " + fe.getNombre() + " lo golpea");
		Archivo.getUnicaInstancia().addInf(i.getNombre() + " gracias a la ayuda de " + pi.getNombre() + " encuentran a " + wes.getNombre()  + " en " + po.getNombre());
end




/*** ACTO 5 || ACTO FINAL  Llegan	a	casa	del	Milagroso	Max	hasta	el	final. ****/


rule "Creacion Acto5"
	agenda-group "Acto5"
	then
		insert(new Curandero());
		insert(new Sacerdote());
		insert(new IglesiaCastillo());
		insert(new CasaMilagrosoMax());
		insert(new MurallaCastillo());
		insert(new PasilloCastillo());
		insert(new PuertaCastillo());
		insert(new SalonCastillo());
		System.out.println("Acto 5");
		Archivo.getUnicaInstancia().addInf("\nActo5\n");
end 


rule "5.1 Creación Personajes Acto5"
	when
		cur: Curandero()
		sac: Sacerdote()
		ig: IglesiaCastillo()
		cs: CasaMilagrosoMax()
		//Auxiliar
	then
		insert(new Max(cs, cur ));
		insert(new Valerie(cs, cur));
		insert(new Obispo(ig, sac));
		//Auxiliar.
		System.out.println("hola");
		
end

rule "5.2 Comprar un milagro"
	when
		pd: PozoDesesperacion()
		cs: CasaMilagrosoMax()
		bb: BrigadaBrutal()
		cur: Curandero()
		i: Inigo(ubicacionActual == pd)
		w: Westley(ubicacionActual == pd, estadoSalud == EstadoSalud.MUERTO)
		f: Fezzik(ubicacionActual == pd, profesion == bb)
		m: Max(ubicacionActual == cs, profesion == cur, estadoSalud == EstadoSalud.VIVO)
	then
		modify(i){
			setUbicacionActual(cs);
		}
		modify(f){
			setUbicacionActual(cs);
		}
		modify(w){
			setUbicacionActual(cs);
		}
	    modify(m){
	          setMotivacion(Motivacion.GANAR_DINERO);
	    }
		Archivo.getUnicaInstancia().addInf(i.getNombre() + " y " + f.getNombre()+ " llevan a " + w.getNombre() + " a " +cs.getNombre());
		//System.out.println("Llegada a la casa del milagrero");
end


rule "5.3 Está Medio Muerto"
	when
		cs: CasaMilagrosoMax()
		i: Inigo(ubicacionActual == cs)
		w: Westley(ubicacionActual == cs, estadoSalud == EstadoSalud.MUERTO)
		f: Fezzik(ubicacionActual == cs)
		m: Max(ubicacionActual == cs, motivacion == Motivacion.GANAR_DINERO)
		v: Valerie(ubicacionActual == cs)
	then
		modify(w){
			setEstadoSalud(EstadoSalud.MEDIO_MUERTO);
		}
		modify(w){
	          setMotivacion(Motivacion.AMOR_VERDADERO);
	    }
	    Archivo.getUnicaInstancia().addInf(m.getNombre() + " informa de que " + w.getNombre()+ " esta " + w.getEstadoSalud().getString()); 
		//System.out.println("Se descubre que está medio muerto");
end

rule "5.4 Discusión de matrimorio"
	when
		cs: CasaMilagrosoMax()
		i: Inigo(ubicacionActual == cs)
		w: Westley(ubicacionActual == cs, estadoSalud == EstadoSalud.MEDIO_MUERTO, motivacion == Motivacion.AMOR_VERDADERO)
		f: Fezzik(ubicacionActual == cs)
		m: Max(ubicacionActual == cs, motivacion == Motivacion.GANAR_DINERO)
		v: Valerie(ubicacionActual == cs)
	then
		modify(m){
	          setEstadoCivil(EstadoCivil.CASADO);
	    }
	    modify(v){
	          setEstadoCivil(EstadoCivil.CASADO);
	    }
	    Relacion fm1 = new FamiliarDe(v);
	    Relacion fm2 = new FamiliarDe(m);
	    ArrayList<Relacion> listM = m.getRelacionesPersonaje();
	    listM.add(fm1);
	    modify(m){
	      setRelacionesPersonaje(listM);
	    }
	     ArrayList<Relacion> listV = v.getRelacionesPersonaje();
	    listV.add(fm2);
	    modify(v){
	      setRelacionesPersonaje(listV);
	    }
		//System.out.println("Max y Valerie tienen una discusión");
		Archivo.getUnicaInstancia().addInf(m.getNombre() +" discute con su mujer " +v.getNombre());
end

rule "5.5 Causa noble"
	when
		cs: CasaMilagrosoMax()
		i: Inigo(ubicacionActual == cs)
		w: Westley(ubicacionActual == cs, estadoSalud == EstadoSalud.MEDIO_MUERTO, motivacion == Motivacion.AMOR_VERDADERO)
		f: Fezzik(ubicacionActual == cs)
		m: Max(ubicacionActual == cs, motivacion == Motivacion.GANAR_DINERO)
		v: Valerie(ubicacionActual == cs)
		princ: Principe()
	then
		//System.out.println("Si Westley revive el príncipe sufrirá humillaciones a mansalba");
		Archivo.getUnicaInstancia().addInf("Informan a " + m.getNombre() + " de que si " + w.getNombre() +" revive, humillará a " + princ.getNombre());
		Relacion od1 = new OdiaA(princ);
    	Relacion od2 = new OdiadoPor(m);
    	
    	ArrayList<Relacion> listaR1 = m.getRelacionesPersonaje();
   		listaR1.add(od1);
	    modify(m){
	          setRelacionesPersonaje(listaR1);
	    }
    	ArrayList<Relacion> listaR2 = princ.getRelacionesPersonaje();
   		listaR2.add(od2);
	    modify(princ){
	          setRelacionesPersonaje(listaR2);
	    }
	    modify(m){
	          setMotivacion(Motivacion.HUMILLAR_PRINCIPE);
	    }
	    
	    //System.out.println("Max hace la píldora");
	    Archivo.getUnicaInstancia().addInf(m.getNombre() + " hace la pildora.");
end

rule "5.6 Plan de asalto"
	when
		cs: CasaMilagrosoMax()
		mc: MurallaCastillo()
		pc: PuertaCastillo(  )
		i: Inigo(ubicacionActual == cs)
		w: Westley(ubicacionActual == cs, estadoSalud == EstadoSalud.MEDIO_MUERTO)
		f: Fezzik(ubicacionActual == cs)
		max: Max(motivacion == Motivacion.HUMILLAR_PRINCIPE)
		ya : Yalin( ubicacionActual ==null )
	then
		modify(i){
			setUbicacionActual(mc);
		}
		modify(f){
			setUbicacionActual(mc);
		}
		modify(w){
			setUbicacionActual(mc),
			setEstadoSalud(EstadoSalud.DEBIL),
			setMotivacion(Motivacion.SALVAR_BUTTERCUP);
		}
		modify(ya){
			setUbicacionActual(pc);
		}
	    //System.out.println("La píldora surge efecto y trazan el plan para entrar al castillo");
	    Archivo.getUnicaInstancia().addInf("La pildora surge efecto y trazan un plan para entrar al castillo");
end

rule "5.7 La Boda oficial primera parte"
	when
		ig: IglesiaCastillo()
		cast: Castillo()
		ap: AposentosPrincesa()
		r: Rey(ubicacionActual == cast)
		b: Buttercup(ubicacionActual == ap) 
		pr: Principe(ubicacionActual == cast)
		cd: Conde(ubicacionActual == cast)
		ob: Obispo(ubicacionActual == ig)
	then
		modify(r){
			setUbicacionActual(ig);
		}
		modify(b){
			setUbicacionActual(ig);
		}
		modify(pr){
			setUbicacionActual(ig);
		}
		modify(cd){
			setUbicacionActual(ig);
		}
	   // System.out.println("Inicio de la boda");
	   Archivo.getUnicaInstancia().addInf("Comienza la boda entre :"+b.getNombre() +" y "+  pr.getNombre());
	    
	   
end

rule "5.8 Inicio del plan"
	when
		pc: PuertaCastillo()
		mc: MurallaCastillo()
		y: Yalin(ubicacionActual == pc)
		i: Inigo(ubicacionActual == mc)
		w: Westley(ubicacionActual == mc)
		f: Fezzik(ubicacionActual == mc)
	then
		modify(i){
			setUbicacionActual(pc);
		}
		modify(f){
			setUbicacionActual(pc);
		}
		modify(w){
			setUbicacionActual(pc);
		}
	    //System.out.println("Inicio del plan para entrar al castillo");
	    Archivo.getUnicaInstancia().addInf("Comienza el plan para entrar en el castillo");
end

rule "5.9 La Boda oficial segunda parte"
	when
		ig: IglesiaCastillo()
		pc : PasilloCastillo()
		r: Rey(ubicacionActual == ig)
		b: Buttercup(ubicacionActual == ig)
		pr: Principe(ubicacionActual == ig)
		cd: Conde(ubicacionActual == ig)
		ob: Obispo(ubicacionActual == ig)
	then
		modify(cd){
			setUbicacionActual(pc);
		}
	    //System.out.println("el conde abandona la boda con algunos guardias");
	    Archivo.getUnicaInstancia().addInf(cd.getNombre() + " abandona la boda con algunos guardias.");
end

rule "5.10 Entrada al Castillo"
	when
		pc: PuertaCastillo()
		pas : PasilloCastillo()
		y: Yalin(ubicacionActual == pc)
		i: Inigo(ubicacionActual == pc)
		w: Westley(ubicacionActual == pc)
		f: Fezzik(ubicacionActual == pc)
	then
	   // System.out.println("Los guardias se asustan y Yalin les da la llave para entrar");
	    modify(i){
			setUbicacionActual(pas);
		}
		modify(f){
			setUbicacionActual(pas);
		}
		modify(w){
			setUbicacionActual(pas);
		}
		//Abria que poner pork salen los guardias corriendo o algo?
		Archivo.getUnicaInstancia().addInf("Los guardias se asustan y Yalin les da llave para entrar");
end

rule "5.11 La Boda oficial fin"
	when
		ig: IglesiaCastillo()
		pc : PasilloCastillo()
		cas : Castillo()
		r: Rey(ubicacionActual == ig)
		b: Buttercup(ubicacionActual == ig)
		pr: Principe(ubicacionActual == ig)
		ob: Obispo(ubicacionActual == ig)
	then
		
		modify(r){
			setUbicacionActual(cas);
		}
		modify(b){
			setEstadoCivil(EstadoCivil.CASADO),
			setUbicacionActual(cas);
		}
		modify(pr){
			setEstadoCivil(EstadoCivil.CASADO),
			setUbicacionActual(null);
		}
	    //System.out.println("Termina la boda");
	    Archivo.getUnicaInstancia().addInf("Finalmente acaba la ceremonia y " + b.getNombre() + " y " +pr.getNombre() + " se casan.");
end

rule "5.12 Encuentro con el Conde"
	when
		pas : PasilloCastillo()
		sc : SalonCastillo()
		c: Conde(ubicacionActual == pas)
		i: Inigo(ubicacionActual == pas)
		w: Westley(ubicacionActual == pas)
		f: Fezzik(ubicacionActual == pas)
	then
	    //System.out.println("iigo mata a los guardias y el conde sale huyendo");
	    Archivo.getUnicaInstancia().addInf(i.getNombre() + " mata a los guardias y " + c.getNombre() + " sale huyendo.");
	    modify(i){
			setUbicacionActual(sc);
		} 
		modify(c){
			setUbicacionActual(sc);
		} 
		//System.out.println("Westley desaparece");
		// y fezzik?
		Archivo.getUnicaInstancia().addInf(w.getNombre() + " desaparece.");
		
	    modify(w){
			setUbicacionActual(null);
		}   
		modify(f){
			setUbicacionActual(null);
		} 
end

rule "Charla con el Rey"
	when
		cas : Castillo()
		ap: AposentosPrincesa()
		r: Rey(ubicacionActual == cas)
		b: Buttercup(ubicacionActual == cas, estadoCivil == EstadoCivil.CASADO)
		eval(b.esConocido(r))
	then
		System.out.println("Charla con el Rey");
		Archivo.getUnicaInstancia().addInf(b.getNombre()+" siente aprecio por " +r.getNombre()+". ");
		Relacion r1 = b.getRelacion(r);
		Relacion r2 = r.getRelacion(b);
		Relacion am1 = new AmigoDe(r);
    	Relacion am2 = new AmigoDe(b);
    	
	    modify(b){
	    	removeRelacion(r1),
	        addRelacion(am1),
			setUbicacionActual(ap),
			setMotivacion(Motivacion.SUICIDARSE);
	    }
	    
	    modify(r){
	    	removeRelacion(r2),
	        addRelacion(am2),
			setUbicacionActual(null);
	    }
	    
	    Archivo.getUnicaInstancia().addInf(b.getNombre()+" le dice a "+r.getNombre()
	    +" que lo ha hecho por él y que se suicidadrá en sus aposentos");
	   
end

rule "Enfrentamiento con el Conde"
	when
		sc : SalonCastillo()
		c: Conde(ubicacionActual == sc)
		i: Inigo(ubicacionActual == sc)
	then
	    Archivo.getUnicaInstancia().addInf("El conde lanza un cuchillo que hiere a Iñigo");
	    modify(i){
			setEstadoSalud(EstadoSalud.HERIDO);
		}   
end

rule "Reencuentro a tiempo"
	when
		ap : AposentosPrincesa()
		b: Buttercup(ubicacionActual == ap, motivacion == Motivacion.SUICIDARSE)
		w: Westley(ubicacionActual == null, estadoSalud == EstadoSalud.DEBIL, motivacion == Motivacion.SALVAR_BUTTERCUP)
	then
		Archivo.getUnicaInstancia().addInf("Buttercup intenta suicidarse pero Westley la detiene");
		modify(b){
			setMotivacion(Motivacion.ESTAR_CON_WESTLEY);
		}
		modify(w){
		setUbicacionActual(ap),
			setMotivacion(Motivacion.ESTAR_CON_BUTTERCUP);
		}
		Archivo.getUnicaInstancia().addInf("Buttercup se lanza a darle amor a Westley, pero este está débil");
end

rule "Prepárate a morir"
	when
		sc : SalonCastillo()
		c: Conde(ubicacionActual == sc)
		i: Inigo(ubicacionActual == sc, estadoSalud == EstadoSalud.HERIDO)
	then
	    Archivo.getUnicaInstancia().addInf("Hola, me llamo Íñigo Montoya. Tú mataste a mi padre. Prepárate a morir");
		modify(c){
			setEstadoSalud(EstadoSalud.MUERTO);
		}
end

rule "Vacío legal"
	when
		ap : AposentosPrincesa()
		b: Buttercup(ubicacionActual == ap, motivacion == Motivacion.ESTAR_CON_WESTLEY, estadoCivil == EstadoCivil.CASADO)
		w: Westley(ubicacionActual == ap, estadoSalud == EstadoSalud.DEBIL, motivacion == Motivacion.ESTAR_CON_BUTTERCUP)
		p: Principe(ubicacionActual == null, estadoCivil == EstadoCivil.CASADO)
	then
		Archivo.getUnicaInstancia().addInf("Buttercup y Westley llegan a la conclusión que al no decir \"Si quiero\" ella no se ha casado");
		modify(b){
			setEstadoCivil(EstadoCivil.SOLTERO);
		}
		modify(p){
			setEstadoCivil(EstadoCivil.SOLTERO);
		}
		Archivo.getUnicaInstancia().addInf("El príncipe aparece");
	    modify(p){
	    	setMotivacion(Motivacion.MATAR_WESTLEY),
			setUbicacionActual(ap);
		}
end

rule "A sufrimiento"
	when
		ap : AposentosPrincesa()
		b: Buttercup(ubicacionActual == ap, estadoCivil == EstadoCivil.SOLTERO)
		w: Westley(ubicacionActual == ap)
		p: Principe(ubicacionActual == ap, estadoCivil == EstadoCivil.SOLTERO, motivacion==Motivacion.MATAR_WESTLEY)
	then
		
		Archivo.getUnicaInstancia().addInf("Westley y el prícipe se van a enfrentar en un duelo \"a sufrimiento\" ");
		
		Archivo.getUnicaInstancia().addInf("Westley le explica al príncipe cómo lo va a mutiliar");
		modify(w){
			setEstadoSalud(EstadoSalud.RECUPERADO);
		}
		modify(p){
			setMotivacion(Motivacion.SEGUIR_VIVO);
		}
		Archivo.getUnicaInstancia().addInf("El príncipe se asusta y lo atan a la silla");
end

rule "Reunión final"
	when
		ap : AposentosPrincesa()
		pC: PatioCastillo()
		sc : SalonCastillo()
		
		b: Buttercup(ubicacionActual == ap, estadoCivil == EstadoCivil.SOLTERO)
		w: Westley(ubicacionActual == ap, estadoSalud == EstadoSalud.RECUPERADO)
		p: Principe(ubicacionActual == ap, motivacion == Motivacion.SEGUIR_VIVO)
		i: Inigo(ubicacionActual == sc, estadoSalud == EstadoSalud.HERIDO)
		f: Fezzik(ubicacionActual == null)
	then
		Archivo.getUnicaInstancia().addInf("Íñigo aparece");
		modify(i){
			setUbicacionActual(ap);
		}
		Archivo.getUnicaInstancia().addInf("Westley realmente sigue débil");
		modify(w){
			setEstadoSalud(EstadoSalud.DEBIL);
		}
		Archivo.getUnicaInstancia().addInf("Fezzik aparece con cuatro caballos");
		modify(f){
			setUbicacionActual(pC);
		}
end

/*rule "Huida del Castillo"

end*/

/*rule "Fin del cuento"

end*/

//Consultas
rule "Consulta Quien" 
	when 
		con: ConsultaQuien()
		p: Personaje (nombre == con.getNombre())
	then
		System.out.println("ENTRO REGLA CONSULTA QUIEN");
		System.out.println(p.toString());
		Archivo.getUnicaInstancia().escribir(p.toString() + "\n\n");
end

rule "Consulta Quien No Existe"
	when 
		con: ConsultaQuien()
		not Personaje (nombre == con.getNombre)
	then
		System.out.println("No sé quien es " + con.getNombre() + " en el acto " + con.getActo());
		Archivo.getUnicaInstancia().escribir("No sé quien es " + con.getNombre() + " en el acto " + con.getActo()+ "\n\n");
end

rule "Consulta Que"
	when
		con: ConsultaQue()
	then
		System.out.println("CONSULTA QUE");
		System.out.print("En el acto " + con.getActo().getNumActo() + "." + " ");
		Archivo.getUnicaInstancia().escribir("En el acto " + con.getActo().getNumActo() + "." + "\n");
		Archivo.getUnicaInstancia().escribirInf();
		Archivo.getUnicaInstancia().escribir("Fin pregunta que\n\n");
		//System.out.println(Archivo.getUnicaInstancia().getpath());
end


rule "Consulta si Sexo"
 	when 
  		consulta : ConsultaSi()
  		eval (Sexo.isValor(consulta.getValorAtributo()))
 		p: Personaje(nombre == consulta.getNombre())
 	then
  		modify(p){
   			setSexo(Sexo.get(consulta.getValorAtributo()));
  		}
 		//insert (consulta.getConsulta()); 
  		System.out.println("SE PUEDE HACER ");
  		System.out.println( p.getNombre() +" es "+ p.getSexo());
end



rule "Consulta si Lugar" 
	salience 10 
	when 
		consulta: ConsultaSi()
		lugar: Lugar(nombre == consulta.getValorAtributo())
		p: Personaje(nombre == consulta.getNombre())
	then 
		modify(p){
			setUbicacionActual(lugar)
		}
		//insert (consulta.getConsulta());
		
		System.out.println("ENTRO EN CONSULTA SI LUGAR Y MODIFICO " + p.getNombre() + " en " + p.getUbicacionActual());
end 


rule "Consulta si Origen"
	salience 10
	when 
		consulta: ConsultaSi()
		eval (Origen.isValor(consulta.getValorAtributo()))
 		p: Personaje(nombre == consulta.getNombre())
	then
		modify(p){
			setOrigen(Origen.get(consulta.getValorAtributo()))
		}
		//insert (consulta.getConsulta());
		
		System.out.println("ENTRO EN CONSULTA SI ORIGEN Y MODIFICO " + p.getNombre() + " en " + p.getOrigen());
end 

rule "Consulta si EstadoSalud"
	salience 10
	when 
		consulta: ConsultaSi()
		eval (EstadoSalud.isValor(consulta.getValorAtributo()))
 		p: Personaje(nombre == consulta.getNombre())
	then
		modify(p){
			setEstadoSalud(EstadoSalud.get(consulta.getValorAtributo()))
		}
		//insert (consulta.getConsulta());
		
		System.out.println("ENTRO EN CONSULTA SI EstadoSalud Y MODIFICO " + p.getNombre() + " en " + p.getEstadoSalud());
end 

rule "Consulta si Profesion" 
	salience 10 
	when 
		consulta: ConsultaSi()
		profesion: Profesion(nombre == consulta.getValorAtributo())
		p: PersonajeCuento(nombre == consulta.getNombre())
	then 
		modify(p){
			setProfesion(profesion)
		}
		//insert (consulta.getConsulta());
		
		System.out.println("ENTRO EN CONSULTA SI profesion Y MODIFICO " + p.getNombre() + " en " + p.getProfesion());
end 
